### ISSUE TITLE
Devices may "forget" firmware.

### ISSUE THREAD

**Issue by attie** [GlasgowEmbedded/glasgow#387] opened 2023-08-05 00:52 UTC
I believe I've seen this a few times - a Glasgow with firmware flashed, will "forget" it, and require firmware to be loaded the first time `glasgow` is invoked.

- It seems that byte @ `0x0` in the EEPROM is being set to `0xC0` (i.e: "_Load custom VID / PID / DID only_")
- `fx2tool` shows that firmware was indeed present (see [gist](https://gist.github.com/attie/a9106c4f9e65fddbb815724fdb306965))
- `glasgow flash` loads the firmware again with no error
- I do not currently have a way to reproduce this issue

**Comment by whitequark** [comment] 2023-08-05 14:13
The code in the firmware that does this is here:

https://github.com/GlasgowEmbedded/glasgow/blob/ba3cb99d0b2bcfd2638ccf0d0418942ec040932f/firmware/main.c#L226-L255

It's called from `main`. But unless `glasgow_config.revision` is for some reason one of specifically `'A'`, `'B'`, or `'C'`, it won't fire.

Since this wouldn't happen with the boards @esden shipped I suspect the cause is something else.

I'm going to close this since it's completely unactionable and there is no reproducer. However, this isn't my way of saying "this issue doesn't matter"—closed issues still stay on the tracker and get searched. If anyone ever hits this again (and is able to provide more context) we will reopen it.

**Comment by whitequark** [comment] 2023-08-05 15:12
Alternatively, we can just remove `config_fixup` entirely. I think it's safe to assume that all of the devices that required the fixup have received it in the four years (git blame points at 2019-03-01) it's been in the codebase.

**Comment by attie** [comment] 2023-08-05 15:46
> Alternatively, we can just remove config_fixup entirely.

I was wondering about that approach too... or wondering if I missed something else performing the write via USB.

**Comment by whitequark** [comment] 2023-08-05 16:49
> or wondering if I missed something else performing the write via USB.

Unless you ran `glasgow flash --no-firmware` or `glasgow factory` I don't see what would issue such a write over USB...

**Closed** 2023-08-05 17:59 UTC
